import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "./Frontend/components/Navbar";
import Footer from "./Frontend/components/Footer";
import { ConvexClientProvider } from "./providers/ConvexProvider";
import { AuthProvider } from "@/context/AuthContext"; // ✅ NEW
import "leaflet/dist/leaflet.css";
import "./globals.css";

export const metadata = {
  title: "Apollo Health Monitoring Alert System",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider> {/* ✅ WRAP EVERYTHING */}
          <ConvexClientProvider>
            <Navbar />
            <main className="pt-18">{children}</main>
            <Footer />
          </ConvexClientProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
