import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "./Components/Navbar";
import "./globals.css";
import Footer from "./Components/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Appolo Health Monitoring Alert System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased pt-16`}
      >
        <Navbar />
       
        {children}
      <Footer/>
      </body>
    </html>
  );
}
